// Generated by nuxt-seo-utils
declare module '#app' {
  import { HeadEntry, HeadTag } from '@unhead/vue/types'

  interface RuntimeNuxtHooks {
    'head:tags': (tag: HeadTag[]) => Promise<void> | void
    'head:entries': (entries: HeadEntry[]) => Promise<void> | void
  }
}
declare module '@unhead/schema' {

  type PublicFiles = '/favicon.png' | '/images/brand/Nuestra Historia-imagen conceptual.jpg' | '/images/brand/aceite-usos.png' | '/images/brand/hero-bruma.png' | '/images/brand/hero-video.mp4' | '/images/brand/logo-pitayalab.png' | '/images/products/Bruma-representacion.png' | '/images/products/aceite-aromatico.jpg' | '/images/products/bruma-jazmin-blanco.png' | '/images/products/bruma-vidanta.png' | '/images/products/bruma-xcaret.png' | '/images/products/vela-clasica.jpg' | '/images/products/vela-mistica.png' | '/images/scents/aroma-jazmin-blanco.png' | '/images/scents/aroma-solara.png' | '/images/scents/aroma-vidanta.png' | '/images/scents/aroma-xcaret.png' | '/images/scents/concepto-ecologico.png' | (string & Record<never, never>)
  type JsFiles = (string & Record<never, never>)

  interface SchemaAugmentations {
    link: import('@unhead/schema').UserTagConfigWithoutInnerContent & {
      href: PublicFiles
    }
    script: import('@unhead/schema').TagUserProperties & {
      src: JsFiles
    }
  }
}

export {}
